### PR TITLE
cmake: improve distro integration allowing to use the standard CMake options

### PR DESCRIPTION
**Pull request by tSed**
Hi all,

This patch makes polarssl more standard wrt CMake options, so makes easier its integration in distros.

Regards,

Samuel

### CODE REVIEW

**Comment by mpg** [comment]
This was actually merge some time ago, closing. Thanks for your contribution.

**Comment by tSed** [comment]
Hi,

I certainly missed something... I cannot find how polarssl behaves WRT the CMake flag BUILD_SHARED_LIBS. :-/

Thanks,

**Comment by mpg** [comment]
Sorry for not being clear, it's merged only in our internal development branch so far, so it's not surprising that you don't see it yet, but it will be in the next release.

**Comment by tSed** [comment]
no pb, thx. :)

**Pull request closed without merging**
