### PR TITLE
Ignore CMake/MSVC-related build files.

### PR DESCRIPTION
**Pull request by madmaxoft**
This adds the files that MSVC2010+ generates during build (including CMake-generated project files) to the git ignore list.

### CODE REVIEW

**Comment by mpg** [comment]
Thanks for your contribution! Unfortunately, two of your patterns cover file we actually use, namely `*.sln` and `*.vcxproj` (in `scripts/data_file` and `visualc/*`). Is it OK for you if we ignore those files only in `include`, `library`, `programs` and `tests`?

**Comment by mpg** [comment]
Actually I went ahead and merged that with the problematic patterns moved to subdirectories. Please let me know if this was not the right thing to do.

**Comment by madmaxoft** [comment]
I must be blind, because I can't see your commit. Did you push it? To which branch?

**Comment by mpg** [comment]
You're not blind, for not it's only in an internal branch, pending review.

**Comment by madmaxoft** [comment]
Could you give me the diff that you merged, so that I can test it in our scenario? I have a feeling it might not work so well, because a .sln file is generated by CMake at PolarSSL's root.

**Comment by mpg** [comment]
Sure, here is the patche I applied just after merging yours:

~~~
diff --git a/.gitignore b/.gitignore
index b42ce61..7dfad2d 100644
--- a/.gitignore
+++ b/.gitignore
@@ -9,8 +9,6 @@ Coverage
 library/polarssl.info

 # MSVC files generated by CMake:
-*.sln
-*.vcxproj
 *.filters

 # MSVC build artifacts:
diff --git a/include/.gitignore b/include/.gitignore
index f3c7a7c..feab4e2 100644
--- a/include/.gitignore
+++ b/include/.gitignore
@@ -1 +1,3 @@
 Makefile
+*.sln
+*.vcxproj
diff --git a/library/.gitignore b/library/.gitignore
index 872219b..39d257a 100644
--- a/library/.gitignore
+++ b/library/.gitignore
@@ -1,3 +1,5 @@
 *.o
 libpolarssl*
 libmbedtls.*
+*.sln
+*.vcxproj
diff --git a/programs/.gitignore b/programs/.gitignore
index a47ef06..ae8617f 100644
--- a/programs/.gitignore
+++ b/programs/.gitignore
@@ -1,4 +1,7 @@
 */Makefile
+*.sln
+*.vcxproj
+
 aes/aescrypt2
 aes/crypt_and_hash
 hash/generic_sum
diff --git a/tests/.gitignore b/tests/.gitignore
index 6590f0f..3c9b0cf 100644
--- a/tests/.gitignore
+++ b/tests/.gitignore
@@ -1,3 +1,6 @@
+*.sln
+*.vcxproj
+
 *.log
 /test_suite*
 data_files/mpi_write
~~~

Indeed it will not be enough if there is an sln file at hte root. For that one I would suggest adding a specific ignore rule with its full name.

Of course, we could use the opposite approach and exclude all sln and vcxproj files except the ones in `visualc/*` and `scripts/data_files` if you can get that to work (I tried it briefly, with no success, but it should be possible).

**Comment by madmaxoft** [comment]
I'll try your changes soon (ish :)

From what I know, once a file is added to Git, it bypasses all the ignore-file mechanisms in Git, so if you don't plan on removing and re-adding the files too often, the global wildcard will still work correctly, your .sln file already added to the repo will still be scanned by Git for modifications etc. If this is an acceptable solution for you, then my patch can still be applied as-is.

**Comment by mpg** [comment]
I agree, but the issue is, we are going to add files from time to time. In `visualc/VS2010` for  example we have one vcxproj file per example program. Those files are generated, so if they are git-ignored, it's reallly way too easy for us to forget to git add them when we create a new example program. I'd like to avoid such an error-prone situation.

**Comment by madmaxoft** [comment]
Fair enough. I'll change the .gitignore to only ignore the specific locations where I get the unwanted files.

**Comment by madmaxoft** [comment]
Do you prefer the ignored files to be listed in the `.gitignore` file in the root folder, or in each specific folder's `.gitignore` file? I can see examples of both approaches, so I can't decide.

**Comment by mpg** [comment]
I think I prefer in folder-specific .gitignore files, but I have no strong opinion here.

**Comment by madmaxoft** [comment]
I have force-pushed the changes over my previous commit.

Now the project files are ignored explicitly in their locations. I kept the other build files (objects, libraries) ignored everywhere.

**Comment by mpg** [comment]
Looks great, thanks! Just to be sure: so cmake doesn't generate anything you want to ignore in the `programs` folder? Because on Unix it sure does generate Makefiles here...

**Comment by madmaxoft** [comment]
Not in my case, I may have this turned off, since we include PolarSSL as a library in a git submodule, and thus turn off all the unneeded stuff such as the tests etc.

**Comment by mpg** [comment]
Ok. I manually merged your last changes, but kept the exclude patterns in `programs` because I think they are useful in the default configuration.

Btw, just curious, in which project are you using PolarSSL?

**Comment by madmaxoft** [comment]
Thanks.

In the one from which this PR originally came - https://github.com/mc-server/MCServer . We're writing an open-source alternative C++ server for Minecraft; the Minecraft protocol itself uses encryption and there's also authorization using HTTPS to mojang.com, that's why we need PolarSSL.

**Pull request closed without merging**
